<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-P9U8PG08" ignored="0" name="Question_1" tests="2" failures="1" timestamp="22 Apr 2020 01:52:43 GMT" time="237.333" errors="0">
  <testcase name="feature" time="101.364" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Zoom_in_zoom_out is fail expected [true] but found [false]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Zoom_in_zoom_out is fail expected [true] but found [false]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: Zoom_in_zoom_out is fail expected [true] but found [false]
at com.cucumber.framework.stepdefinition.Mapsyn_step.Zoom_in_zoom_out.verify_the_Map_link(Zoom_in_zoom_out.java:63)
at âœ½.Then Verify the Map link(featurefile/Mapsynq/Maps.feature:14)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="135.271" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Question_1 -->
